### ISSUE TITLE
missed two files: test_cartpole.sh test_gridworld.sh

### ISSUE THREAD

**Issue by ling-k** [ElisevanderPol/mdp-homomorphic-networks#1]
Hi Elise, 
I couldn't find **test_cartpole.sh** and **test_gridworld.sh**. Could you please check them? Thanks.

**Comment by ElisevanderPol** [comment]
Thank you for letting me know! Files have been added, see commit bfe6a9457771621e3c6d2cd65c83caccb6ec0798
