### ISSUE TITLE
A question about computing gain

### ISSUE THREAD

**Issue by vincent341** [ElisevanderPol/mdp-homomorphic-networks#3]
Hi. Would you mind letting me know what "[gain](https://github.com/ElisevanderPol/symmetrizer/blob/8dae02bee2ba7132ae4fb07e07020767d280842c/symmetrizer/nn/modules.py#L81)" is for? Why compute gain? Thanks very much.

**Comment by ElisevanderPol** [comment]
Answered in [a duplicate issue](https://github.com/ElisevanderPol/symmetrizer/issues/1#issuecomment-988634846).
